


ps2-input: (compile-expansion "./PS2 Input")



compile-expansion folder:
    propan \
        --output "{{folder}}/firmware.bin" \
        --format flat \
        "{{folder}}/firmware.propan" 
    ashet-exp encode \
        --output "{{folder}}/eeprom.bin" \
        --firmware "{{folder}}/firmware.bin" \
        "{{folder}}/eeprom.json"
    hexdump -C "{{folder}}/eeprom.bin" \
        | tee "{{folder}}/eeprom.hex"