name: CAD Files

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
    case:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                sudo apt-get -y update
                sudo apt-get -y install openscad just
            
            - name: Render files
              run: |
                cd Hardware/Case
                just
            
            - uses: actions/upload-artifact@v4
              with:
                name: case
                path: Hardware/Case/render
