name: ERC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:          
  drc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Update System
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-8.0-releases
          sudo apt-get -y update
      
      - name: Install Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: kicad just
          version: 1.0
      
      - name: KiCAD Version
        run: |
          kicad-cli version
      
      - name: Run ERC
        run: |
          cd Hardware
          just erc-schematics
      
      - uses: actions/upload-artifact@v4
        with:
          name: ERC
          path: Hardware/.render/erc
    
